version: '3.3'

networks:
  app-network:
    driver: bridge

services:
  app:
    build: ./app
    ports:
      - "3096:3000"
    env_file:
      - ./app/.env
    volumes:
      - type: bind
        source: ./app
        target: /home/app/
      - /home/app/node_modules
    depends_on:
      - db
    networks:
      - app-network
    command: sh -c 'yarn && yarn dev'
  db:
    container_name: mypsql
    image: postgres
    env_file:
      - ./app/.env
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - ./db:/var/lib/postgresql/data
  pgadmin:
    container_name: mypgadmin
    image: dpage/pgadmin4
    env_file:
      - ./app/.env
    ports:
      - "5050:80"
    networks:
      - app-network
    links:
      - db:pg-server
    logging:
      driver: "none"
volumes:
  db: